[package]
name = "async-rustls"
version = "0.1.0"
authors = [
  "Alex Crichton <alex@alexcrichton.com>",
  "quininer kel <quininer@live.com>",
  "Stjepan Glavina <stjepang@gmail.com>",
]
edition = "2018"
description = "WIP"
license = "Apache-2.0 OR MIT"

[dependencies]
futures-lite = "1.10.1"
rustls = "0.18"
webpki = "0.21"

[dev-dependencies]
lazy_static = "1"
smol = "1.2.3"
webpki-roots = "0.20"
